# Library

In [1]:
# Library
import pandas as pd
import numpy as np
import pyexasol

In [2]:
import os

In [3]:
df1_fold = 'D:/data/big2/BD1/df'
raw1_fold = 'D:/data/big2/BD1/raw'

In [4]:
# 소수점 옵션
pd.options.display.float_format = '{:.2f}'.format
# pd.reset_option('display.float_format')

# Server

In [2]:
# # insider db
# wd = pyexasol.connect(dsn='172.29.135.35/F99FAB2444F86051A9A467F6313FAAB48AF7C4760663430958E3B89A9DC53361:8563', user='sys', password='exasol', compression=True, schema='VSYSD')
# we = pyexasol.connect(dsn='172.29.135.35/F99FAB2444F86051A9A467F6313FAAB48AF7C4760663430958E3B89A9DC53361:8563', user='sys', password='exasol', compression=True, schema='vsyse')

In [8]:
# exasol db
ws = pyexasol.connect(dsn='dev.openankus.org:8563', user='sys', password='djslzja', compression=True, schema='VSYS')
wd = pyexasol.connect(dsn='dev.openankus.org:8563', user='sys', password='djslzja', compression=True, schema='VSYSD')
we = pyexasol.connect(dsn='dev.openankus.org:8563', user='sys', password='djslzja', compression=True, schema='VSYSE')

# Data

In [3]:
# 9.6s
df = we.export_to_pandas("SELECT * from STD_BD_GRD5_LEM_PRIO_ORD_SELCT_CURSTT;")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125999 entries, 0 to 1125998
Data columns (total 16 columns):
 #   Column               Non-Null Count    Dtype  
---  ------               --------------    -----  
 0   VIN                  1125999 non-null  object 
 1   VHRNO                1125999 non-null  object 
 2   STDG_CD              1125999 non-null  int64  
 3   CTPV_NM              1125999 non-null  object 
 4   SGG_NM               1125980 non-null  object 
 5   YRIDNW               1125999 non-null  int64  
 6   PURPS_CD2            1125999 non-null  object 
 7   VHCTY_CD             1125999 non-null  object 
 8   VHCTY_TY             1125999 non-null  object 
 9   RDCDVC               144534 non-null   object 
 10  PRIO_GRD             1125999 non-null  int64  
 11  SELCT_PNT            666281 non-null   float64
 12  NOLOD_SMO_MEVLU1     769835 non-null   float64
 13  DY_AVRG_DRVNG_DSTNC  817694 non-null   float64
 14  RCNT_INSP_ELPSD_WHL  817694 non-null   float64
 15

In [5]:
df.sort_values('SELCT_PNT', ascending=False).head(10)

VIN      VHRNO     STDG_CD CTPV_NM SGG_NM  YRIDNW   
459720  KMYKP17CPYU414954    05루9403  2871025022   인천광역시    강화군    2000  \
459721  KMFLA18EP7C022656  충남94바1614  4427010100    충청남도    당진시    2007   
459722       410234338117    90더7549  4137010300     경기도    오산시    2002   
459723  KN3HDP3361K740793    86두9741  4215033024     강원도    강릉시    2001   
459724  KMFGA17PP7C067736  서울85바5177  1150010500   서울특별시    강서구    2007   
459725  KMFLA18EP7C020816  경기89아3220  4141010400     경기도    군포시    2007   
459726  KMHSC81VP1U107601    52어8475  4272031029     강원도    홍천군    2001   
459727  KL3C5CHF17K001032  전북86사9320  4571025326    전라북도    완주군    2007   
459728  KMFLA19AP2C029792  경기90아2687  4163011600     경기도    양주시    2002   
459729  KMFZCS7JP7U277255    91고7943  4139011800     경기도    시흥시    2007   

       PURPS_CD2 VHCTY_CD VHCTY_TY RDCDVC  PRIO_GRD  SELCT_PNT   
459720       자가용       승합       중형    NaN         3    25429.0  \
459721       영업용       화물       대형    NaN         3      572.0   
459722       자가용       화물       대형    DPF         3      561.0   
459723       자가용       화물       중형    NaN         3      516.0   
459724       영업용       화물       중형    NaN         3      503.0   
459725       영업용       화물       대형    DPF         3      491.0   
459726       자가용       승용       중형    NaN         3      437.0   
459727       영업용       화물       대형    NaN         3      426.0   
459728       영업용       화물       중형    DPF         3      418.0   
459729       자가용       화물       소형    NaN         3      394.0   

        NOLOD_SMO_MEVLU1  DY_AVRG_DRVNG_DSTNC  RCNT_INSP_ELPSD_WHL   
459720              21.0        102073.363010                263.0  \
459721               5.0          1185.562304               1065.0   
459722               0.0          1278.551677                939.0   
459723             999.9            50.910037               1023.0   
459724              12.0          1629.004208                368.0   
459725               1.0          1498.629521                457.0   
459726             999.9            44.664576                723.0   
459727               8.0          1416.968850                273.0   
459728              26.0           996.542561                631.0   
459729               7.0           705.200585                835.0   

        RUN_LMT_NOCS  
459720           5.0  
459721           0.0  
459722           0.0  
459723           0.0  
459724           0.0  
459725           0.0  
459726           1.0  
459727           6.0  
459728           0.0  
459729           1.0

## STD_BD_GRD4_ELPDSRC_CURSTT

In [6]:
# 1.3s
df = pd.read_csv(os.path.join(df1_fold, 'STD_BD_GRD4_ELPDSRC_CURSTT.csv'))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156240 entries, 0 to 1156239
Data columns (total 12 columns):
 #   Column               Non-Null Count    Dtype  
---  ------               --------------    -----  
 0   CRTR_YM              1156240 non-null  float64
 1   VIN                  1156240 non-null  object 
 2   STDG_CD              1156240 non-null  int64  
 3   VHCTY_CD             1156240 non-null  object 
 4   PURPS_CD2            1156240 non-null  object 
 5   FUEL_CD              1156240 non-null  object 
 6   VHCTY_TY             1156240 non-null  object 
 7   CTPV                 1156240 non-null  object 
 8   SGG                  1156240 non-null  object 
 9   ELPDSRC_STTS_CD      6696 non-null     object 
 10  ELPDSRC_LST_APRV_YN  6696 non-null     object 
 11  LOAD_DT              1156240 non-null  int64  
dtypes: float64(1), int64(2), object(9)
memory usage: 105.9+ MB


In [7]:
df['ELPDSRC_LST_APRV_YN'].unique()

array([nan, 'Y'], dtype=object)

In [10]:
# 1.3s
df = we.export_to_pandas("SELECT * FROM STD_BD_GRD4_ELPDSRC_CURSTT;")
df.info()

C:\Users\kbjung\AppData\Roaming\Python\Python39\site-packages\pyexasol\callback.py:42: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  return pandas.read_csv(pipe, skip_blank_lines=False, **kwargs)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2378648 entries, 0 to 2378647
Data columns (total 11 columns):
 #   Column                Dtype  
---  ------                -----  
 0   CRTR_YM               float64
 1   VIN                   object 
 2   MANG_MNG_NO           object 
 3   CTPV                  object 
 4   SGG                   object 
 5   VHCTY_CD              object 
 6   VHCTY_TY              object 
 7   PURPS_CD2             object 
 8   FUEL_CD               object 
 9   ELPDSRC_STTS_CD       object 
 10  ELPDSRC_LAST_APRV_YN  object 
dtypes: float64(1), object(10)
memory usage: 199.6+ MB


In [12]:
df['ELPDSRC_LAST_APRV_YN'].value_counts()

ELPDSRC_LAST_APRV_YN
Y    366244
Name: count, dtype: int64

# STD_BJCD_INFO(법정동코드)

In [4]:
# 1.3s
code = wd.export_to_pandas("SELECT STDG_CD, STDG_CTPV_CD, STDG_SGG_CD, STDG_CTPV_NM, STDG_SGG_NM FROM STD_BJCD_INFO;")
code.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47916 entries, 0 to 47915
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   STDG_CD       47916 non-null  int64 
 1   STDG_CTPV_CD  47916 non-null  int64 
 2   STDG_SGG_CD   47916 non-null  int64 
 3   STDG_CTPV_NM  47916 non-null  object
 4   STDG_SGG_NM   47892 non-null  object
dtypes: int64(3), object(2)
memory usage: 1.8+ MB


In [5]:
code.columns

Index(['STDG_CD', 'STDG_CTPV_CD', 'STDG_SGG_CD', 'STDG_CTPV_NM',
       'STDG_SGG_NM'],
      dtype='object')

In [6]:
code_ch_col = {
    'STDG_CD':'법정동코드', 
    'STDG_CTPV_NM':'시도', 
    'STDG_SGG_NM':'시군구', 
    'STDG_CTPV_CD':'시도코드', 
    'STDG_SGG_CD':'시군구코드',
}

In [7]:
coder = code.rename(columns=code_ch_col)
coder.columns

Index(['법정동코드', '시도코드', '시군구코드', '시도', '시군구'], dtype='object')

In [11]:
coder[coder['시도'].str.contains('강원특별') == True]

법정동코드  시도코드  시군구코드       시도  시군구
43594  5183035042    51    830  강원특별자치도  양양군
46444  5100000000    51      0  강원특별자치도  NaN
46445  5111000000    51    110  강원특별자치도  춘천시
46446  5111010100    51    110  강원특별자치도  춘천시
46447  5111010200    51    110  강원특별자치도  춘천시
...           ...   ...    ...      ...  ...
47911  5183035037    51    830  강원특별자치도  양양군
47912  5183035038    51    830  강원특별자치도  양양군
47913  5183035039    51    830  강원특별자치도  양양군
47914  5183035040    51    830  강원특별자치도  양양군
47915  5183035041    51    830  강원특별자치도  양양군

[1473 rows x 5 columns]

## STD_BD_GRD4_RESULT

In [7]:
# 1.3s
df = pd.read_csv(os.path.join(df1_fold, 'STD_BD_GRD4_MLSFC_RSLT.csv'))
df.info()

C:\Users\kbjung\AppData\Local\Temp\ipykernel_412\4284546125.py:2: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(df1_fold, 'STD_BD_GRD4_MLSFC_RSLT.csv'))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1515737 entries, 0 to 1515736
Data columns (total 14 columns):
 #   Column        Non-Null Count    Dtype 
---  ------        --------------    ----- 
 0   LOAD_DT       1515737 non-null  int64 
 1   VIN           1515737 non-null  object
 2   MANG_MNG_NO   1515737 non-null  object
 3   VHCTY_CD      1515735 non-null  object
 4   PURPS_CD2     1515737 non-null  object
 5   YRIDNW        1515737 non-null  int64 
 6   VHCTY_TY      1515737 non-null  object
 7   FUEL_CD       1515666 non-null  object
 8   STDG_CD       1515737 non-null  int64 
 9   CTPV_NM       1515737 non-null  object
 10  SGG_NM        1515732 non-null  object
 11  DPF_MNTNG_YN  1114160 non-null  object
 12  GRD4_MLSFC    1515737 non-null  object
 13  STDG_CD_MOD   1515737 non-null  int64 
dtypes: int64(4), object(10)
memory usage: 161.9+ MB


In [11]:
df['YRIDNW'].describe()

count   1515737.00
mean       2005.81
std           6.85
min        1901.00
25%        2006.00
50%        2009.00
75%        2010.00
max        2020.00
Name: YRIDNW, dtype: float64

In [12]:
df.loc[df['YRIDNW'] == 1901]

LOAD_DT           VIN     MANG_MNG_NO VHCTY_CD PURPS_CD2  YRIDNW   
1420990  20230715  119111200127  20019500040000       승용       개인용    1901  \

        VHCTY_TY FUEL_CD     STDG_CD CTPV_NM SGG_NM DPF_MNTNG_YN GRD4_MLSFC   
1420990       중형     휘발유  4711133025    경상북도    포항시          NaN          B  \

         STDG_CD_MOD  
1420990   4711100000

In [24]:
df.loc[df['YRIDNW'] == 1968]

LOAD_DT          VIN     MANG_MNG_NO VHCTY_CD PURPS_CD2  YRIDNW   
1515735  20230715  SL68T032460  10017500140000       승용       개인용    1968  \

        VHCTY_TY FUEL_CD     STDG_CD CTPV_NM SGG_NM DPF_MNTNG_YN GRD4_MLSFC   
1515735       대형     휘발유  1165010100   서울특별시    서초구          NaN          B  \

         STDG_CD_MOD  
1515735   1165000000

In [26]:
df.loc[df['YRIDNW'] == 1973]

LOAD_DT           VIN     MANG_MNG_NO VHCTY_CD PURPS_CD2  YRIDNW   
1297448  20230715  417313295785  30111800000286       승용       개인용    1973  \

        VHCTY_TY FUEL_CD     STDG_CD CTPV_NM SGG_NM DPF_MNTNG_YN GRD4_MLSFC   
1297448       소형     휘발유  4159012900     경기도    화성시          NaN          B  \

         STDG_CD_MOD  
1297448   4159000000

In [19]:
# 1.3s
rs = pd.read_csv(os.path.join(df1_fold, 'STD_BD_GRD4_CAR_CURSTT.csv'))
rs.info()

C:\Users\kbjung\AppData\Local\Temp\ipykernel_412\3793727572.py:2: DtypeWarning: Columns (3,16) have mixed types. Specify dtype option on import or set low_memory=False.
  rs = pd.read_csv(os.path.join(df1_fold, 'STD_BD_GRD4_CAR_CURSTT.csv'))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1515736 entries, 0 to 1515735
Data columns (total 26 columns):
 #   Column                 Non-Null Count    Dtype  
---  ------                 --------------    -----  
 0   LOAD_DT                1515736 non-null  int64  
 1   CRTR_YM                1515736 non-null  float64
 2   VIN                    1515736 non-null  object 
 3   MANG_MNG_NO            1515736 non-null  object 
 4   VHCTY_CD               1515734 non-null  object 
 5   PURPS_CD2              1515736 non-null  object 
 6   YRIDNW                 1515736 non-null  int64  
 7   VHCTY_TY               1515736 non-null  object 
 8   FUEL_CD                1515665 non-null  object 
 9   STDG_CD                1515736 non-null  int64  
 10  CTPV_NM                1515736 non-null  object 
 11  SGG_NM                 1515731 non-null  object 
 12  VHCNM                  1515736 non-null  object 
 13  MNFCTR_NM              1505649 non-null  object 
 14  EXHST_GAS_CERT_NO_

In [23]:
rs.loc[rs['VIN'] == '119111200127'].values

array([[20230719, 2022.12, '119111200127', 20019500040000, '승용', '개인용',
        1901, '중형', '휘발유', 4711133025, '경상북도', '포항시', '크로마터보i.e', nan,
        nan, 4, nan, nan, nan, nan, nan, nan, nan, nan, 4711100000, 'B']],
      dtype=object)

In [25]:
rs.loc[rs['VIN'] == 'SL68T032460'].values

array([[20230719, 2022.12, 'SL68T032460', '10017500140000', '승용', '개인용',
        1968, '대형', '휘발유', 1165010100, '서울특별시', '서초구', '쏘나타 오토매틱',
        '현대자동차', 'KMY-HD-03', 4, nan, nan, nan, nan, nan, nan, nan, nan,
        1165000000, 'B']], dtype=object)

In [27]:
rs.loc[rs['VIN'] == '417313295785'].values

array([[20230719, 2022.12, '417313295785', '30111800000286', '승용', '개인용',
        1973, '소형', '휘발유', 4159012900, '경기도', '화성시', '폭스바겐짚컨버터블',
        '**기타**', nan, 4, nan, '부하검사(ASM-Idling)', '종합검사', 'N', 1.81,
        'N', 101.0, 1435.0, 4159000000, 'B']], dtype=object)