# Library

In [1]:
import pandas as pd
import numpy as np
import os

## 임시 파일 테스트

In [2]:
df1 = pd.DataFrame({'a':[1, 2, 3, 4], 'b':[2, 3, 4, 5], 'c':['a', 'b', 'c', 'd'], 'd':[400, 300, 200, 400]})
df2 = pd.DataFrame({'a':[10, 20 ,30, 40], 'b1':[20, 30, 40, 50], 'c':['30', '40', '50', '60'], 'd':['d1', 'd2', 'd3', 'd4']})
df1.shape, df2.shape

((4, 4), (4, 4))

In [73]:
df = pd.concat([df1, df2], ignore_index=False)
df

a    b   c    d    b1
0   1  2.0   a  400   NaN
1   2  3.0   b  300   NaN
2   3  4.0   c  200   NaN
3   4  5.0   d  400   NaN
0  10  NaN  30   d1  20.0
1  20  NaN  40   d2  30.0
2  30  NaN  50   d3  40.0
3  40  NaN  60   d4  50.0

In [74]:
np_df = df.to_numpy()
np_df

array([[1, 2.0, 'a', 400, nan],
       [2, 3.0, 'b', 300, nan],
       [3, 4.0, 'c', 200, nan],
       [4, 5.0, 'd', 400, nan],
       [10, nan, '30', 'd1', 20.0],
       [20, nan, '40', 'd2', 30.0],
       [30, nan, '50', 'd3', 40.0],
       [40, nan, '60', 'd4', 50.0]], dtype=object)

In [92]:
col = df.columns

In [79]:
np_df.shape

(8, 5)

In [35]:
col = df.columns
col1 = df['a'].to_numpy()
col2 = df['b'].to_numpy()
col3 = df['c'].to_numpy()
col4 = df['d'].to_numpy()
col5 = df['b1'].to_numpy()

In [93]:
np.savez('np_data/test', 컬럼1=col1, 컬럼2=col2, 컬럼3=col3, 컬럼4=col4, 컬럼5=col5)

In [64]:
np.savez_compressed('np_data/compressed_test', 컬럼1=col1, 컬럼2=col2, 컬럼3=col3, 컬럼4=col4, 컬럼5=col5)

In [84]:
%%time
load_df = np.load('np_data/test.npz', allow_pickle=True)
load_df

Wall time: 0 ns


In [99]:
np.savez('np_data/test', data=np_df, col=col)

In [100]:
%%time
load_df = np.load('np_data/test.npz', allow_pickle=True)
load_df

Wall time: 11 ms


In [101]:
load_df.files

['data', 'col']

In [102]:
load_df['data']

array([[1, 2.0, 'a', 400, nan],
       [2, 3.0, 'b', 300, nan],
       [3, 4.0, 'c', 200, nan],
       [4, 5.0, 'd', 400, nan],
       [10, nan, '30', 'd1', 20.0],
       [20, nan, '40', 'd2', 30.0],
       [30, nan, '50', 'd3', 40.0],
       [40, nan, '60', 'd4', 50.0]], dtype=object)

In [103]:
load_df['col']

array(['a', 'b', 'c', 'd', 'b1'], dtype=object)

In [104]:
pd.DataFrame(load_df['data'], columns=col)

a    b   c    d    b1
0   1  2.0   a  400   NaN
1   2  3.0   b  300   NaN
2   3  4.0   c  200   NaN
3   4  5.0   d  400   NaN
4  10  NaN  30   d1  20.0
5  20  NaN  40   d2  30.0
6  30  NaN  50   d3  40.0
7  40  NaN  60   d4  50.0

In [69]:
data_df = pd.DataFrame.from_dict({x:load_df[x] for x in load_df.files})
data_df

컬럼1  컬럼2 컬럼3  컬럼4   컬럼5
0    1  2.0   a  400   NaN
1    2  3.0   b  300   NaN
2    3  4.0   c  200   NaN
3    4  5.0   d  400   NaN
4   10  NaN  30   d1  20.0
5   20  NaN  40   d2  30.0
6   30  NaN  50   d3  40.0
7   40  NaN  60   d4  50.0

# 4등급 등록&제원정보로 테스트

In [2]:
ods_fold = 'D:/data/big2/ODS'

In [112]:
# about 33s
file_name = '[ODS][G4]등록정보&제원정보(2022.12.28).csv'
df = pd.read_csv(os.path.join(ods_fold, file_name), encoding='cp949', low_memory=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1898816 entries, 0 to 1898815
Data columns (total 49 columns):
 #   Column        Dtype  
---  ------        -----  
 0   차량관리번호        object 
 1   차량등록번호        object 
 2   본거지법정동코드      int64  
 3   소유자구분         object 
 4   차종_등록정보       object 
 5   용도            object 
 6   현재회원번호        object 
 7   차대번호          object 
 8   최초등록일자        int64  
 9   차량연식          int64  
 10  차량제작일자        float64
 11  배출가스검사유효일자    float64
 12  제원관리번호        object 
 13  배출가스인증번호      object 
 14  배출가스등급        object 
 15  저공해조치YN(미사용)  object 
 16  저공해조치종류       float64
 17  저공해조치구조변경YN   object 
 18  차량등록번호숫자정보    int64  
 19  차량말소YN        object 
 20  최초회원번호        object 
 21  취득일자          object 
 22  취득금액          float64
 23  생성일시_등록정보     object 
 24  수정일시_등록정보     object 
 25  차명            object 
 26  차종_제원정보       object 
 27  차종분류          object 
 28  차종유형(소분류)     object 
 29  자동차형식         object 
 30  제작사명          obje

In [113]:
df.isnull().sum()

차량관리번호                0
차량등록번호                0
본거지법정동코드              0
소유자구분                 0
차종_등록정보               2
용도                    0
현재회원번호              839
차대번호                  0
최초등록일자                0
차량연식                  0
차량제작일자           188717
배출가스검사유효일자           15
제원관리번호                0
배출가스인증번호         159076
배출가스등급                0
저공해조치YN(미사용)        216
저공해조치종류         1898600
저공해조치구조변경YN           1
차량등록번호숫자정보            0
차량말소YN                0
최초회원번호             4799
취득일자             110182
취득금액              90836
생성일시_등록정보             0
수정일시_등록정보        596210
차명                    0
차종_제원정보               0
차종분류                  0
차종유형(소분류)             0
자동차형식               649
제작사명              12123
연료                   89
엔진형식               2138
공차중량            1898816
총중량                  32
적재중량                647
엔진출력                754
배기량                  14
승차인원                  1
차량길이                141
차량너비                141
차량높이            

In [108]:
# about 
np.savez_compressed('np_data/[G4]등록&제원정보(2022.12.28)', col=df.columns, data=df.to_numpy())

In [5]:
ndf = np.load('np_data/[G4]등록&제원정보(2022.12.28).npz', allow_pickle=True)

In [6]:
ndf.files

['col', 'data']

In [116]:
# about 16s
df2 = pd.DataFrame(ndf['data'], columns=ndf['col'])
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1898816 entries, 0 to 1898815
Data columns (total 49 columns):
 #   Column        Dtype 
---  ------        ----- 
 0   차량관리번호        object
 1   차량등록번호        object
 2   본거지법정동코드      object
 3   소유자구분         object
 4   차종_등록정보       object
 5   용도            object
 6   현재회원번호        object
 7   차대번호          object
 8   최초등록일자        object
 9   차량연식          object
 10  차량제작일자        object
 11  배출가스검사유효일자    object
 12  제원관리번호        object
 13  배출가스인증번호      object
 14  배출가스등급        object
 15  저공해조치YN(미사용)  object
 16  저공해조치종류       object
 17  저공해조치구조변경YN   object
 18  차량등록번호숫자정보    object
 19  차량말소YN        object
 20  최초회원번호        object
 21  취득일자          object
 22  취득금액          object
 23  생성일시_등록정보     object
 24  수정일시_등록정보     object
 25  차명            object
 26  차종_제원정보       object
 27  차종분류          object
 28  차종유형(소분류)     object
 29  자동차형식         object
 30  제작사명          object
 31  연료            object
 32

In [117]:
df2.isnull().sum()

차량관리번호                0
차량등록번호                0
본거지법정동코드              0
소유자구분                 0
차종_등록정보               2
용도                    0
현재회원번호              839
차대번호                  0
최초등록일자                0
차량연식                  0
차량제작일자           188717
배출가스검사유효일자           15
제원관리번호                0
배출가스인증번호         159076
배출가스등급                0
저공해조치YN(미사용)        216
저공해조치종류         1898600
저공해조치구조변경YN           1
차량등록번호숫자정보            0
차량말소YN                0
최초회원번호             4799
취득일자             110182
취득금액              90836
생성일시_등록정보             0
수정일시_등록정보        596210
차명                    0
차종_제원정보               0
차종분류                  0
차종유형(소분류)             0
자동차형식               649
제작사명              12123
연료                   89
엔진형식               2138
공차중량            1898816
총중량                  32
적재중량                647
엔진출력                754
배기량                  14
승차인원                  1
차량길이                141
차량너비                141
차량높이            

In [7]:
ndf['col']

array(['차량관리번호', '차량등록번호', '본거지법정동코드', '소유자구분', '차종_등록정보', '용도', '현재회원번호',
       '차대번호', '최초등록일자', '차량연식', '차량제작일자', '배출가스검사유효일자', '제원관리번호',
       '배출가스인증번호', '배출가스등급', '저공해조치YN(미사용)', '저공해조치종류', '저공해조치구조변경YN',
       '차량등록번호숫자정보', '차량말소YN', '최초회원번호', '취득일자', '취득금액', '생성일시_등록정보',
       '수정일시_등록정보', '차명', '차종_제원정보', '차종분류', '차종유형(소분류)', '자동차형식', '제작사명',
       '연료', '엔진형식', '공차중량', '총중량', '적재중량', '엔진출력', '배기량', '승차인원', '차량길이',
       '차량너비', '차량높이', '원산지명', '삭제YN', '승인일자', '구동형식', '변속기종류',
       '생성일시_제원정보', '수정일시_제원정보'], dtype=object)

In [8]:
np.where(ndf['col'] == '차대번호')

(array([7], dtype=int64),)

In [10]:
# about 15s
ndf['data'][:5, 7]

array(['CN-62-T-2213', 'SL68T032460', '2T1CF2897YC359923',
       'KNADA2322HS004198', 'KNADA2322HS004360'], dtype=object)

In [11]:
# about 15s
temp = ndf['data'][:, 7]