# Library

In [1]:
import pandas as pd
import numpy as np
import os
from datetime import datetime

# fold path

In [2]:
ods_fold = 'D:/data/big2/ODS'
fold = 'D:/data/big2/BD1_4등급_데이터_점검1'

In [3]:
# 소수점 옵션
pd.options.display.float_format = '{:.2f}'.format
# pd.reset_option('display.float_format')

# 9MY-KM-14-22 차량 확인

## 등록&제원정보(말소제거)

In [4]:
# about 6m 48s
file_name = '[ODS]등록정보&제원정보(말소제거)(2022.12.28).csv'
car_info = pd.read_csv(os.path.join(ods_fold, file_name), encoding='cp949', low_memory=False)
car_info.info()

In [ ]:
car_info.columns

Index(['차량관리번호', '차량등록번호', '본거지법정동코드', '소유자구분', '차종_등록정보', '용도', '현재회원번호',
       '차대번호', '최초등록일자', '차량연식', '차량제작일자', '배출가스검사유효일자', '제원관리번호', '배출가스인증번호',
       '배출가스등급', '저공해조치YN(미사용)', '저공해조치종류', '저공해조치구조변경YN', '차량등록번호숫자정보',
       '차량말소YN', '최초회원번호', '취득일자', '취득금액', '생성일시_등록정보', '수정일시_등록정보', '차명',
       '차종_제원정보', '차종분류', '차종유형(소분류)', '자동차형식', '제작사명', '연료', '엔진형식', '공차중량',
       '총중량', '적재중량', '엔진출력', '배기량', '승차인원', '차량길이', '차량너비', '차량높이', '원산지명',
       '삭제YN', '승인일자', '구동형식', '변속기종류', '생성일시_제원정보', '수정일시_제원정보'],
      dtype='object')

In [6]:
car_info[car_info['배출가스인증번호'] == '9MY-KM-14-22'].shape

(94868, 49)

In [14]:
car_info.loc[car_info['배출가스인증번호'] == '9MY-KM-14-22', '배출가스등급'].value_counts(dropna=False)

3    94868
Name: 배출가스등급, dtype: int64

In [21]:
car_info.loc[car_info['배출가스인증번호'] == '9MY-KM-14-22', '차량말소YN'].value_counts(dropna=False)

N    87217
Y     7651
Name: 차량말소YN, dtype: int64

## 4등급_차량_리스트_양식_result

In [17]:
# about 27s
file_name = '[병합]4등급_차량_리스트_양식_result.csv'
result = pd.read_csv(os.path.join(fold, file_name), encoding='cp949', low_memory=False)
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1153813 entries, 0 to 1153812
Data columns (total 64 columns):
 #   Column     Non-Null Count    Dtype  
---  ------     --------------    -----  
 0   차대번호       1153813 non-null  object 
 1   차량번호_x     1153813 non-null  object 
 2   제원관리번호     1153813 non-null  object 
 3   차종_원본      1153813 non-null  object 
 4   용도         1153813 non-null  object 
 5   최초등록일      1153813 non-null  int64  
 6   연식         1153813 non-null  int64  
 7   제작일자       1153809 non-null  float64
 8   검사유효일      1153810 non-null  float64
 9   배출가스인증번호   1146663 non-null  object 
 10  등급         1153813 non-null  int64  
 11  차명_x       1153813 non-null  object 
 12  차종분류       1153813 non-null  object 
 13  차종유형       1153813 non-null  object 
 14  자동차형식      1153812 non-null  object 
 15  제작사명       1153795 non-null  object 
 16  연료         1153813 non-null  object 
 17  엔진형식_x     1153813 non-null  object 
 18  총중량        1153813 non-null  float64
 19  

In [18]:
result.columns

Index(['차대번호', '차량번호_x', '제원관리번호', '차종_원본', '용도', '최초등록일', '연식', '제작일자',
       '검사유효일', '배출가스인증번호', '등급', '차명_x', '차종분류', '차종유형', '자동차형식', '제작사명',
       '연료', '엔진형식_x', '총중량', '적재중량', '엔진출력', '배기량', '법정동코드', '시도명', '시군구명',
       '소유자구분', '말소여부', '일치유무', '사용연료', '주행거리', '차명_y', '차량번호_y', '차종', '차량연식',
       '엔진형식_y', '검사방법', '검사일자', '검사종류', '검사판정시각', '검사판정', '산소값', '이산화탄소값',
       '무부하매연판정1', '무부하매연판정2', '무부하매연판정3', '무부하매연판정4', '무부하매연판정5', '무부하매연판정6',
       '무부하매연허용치1', '무부하매연허용치2', '무부하매연허용치3', '무부하매연허용치4', '무부하매연허용치5',
       '무부하매연허용치6', '무부하매연측정치1', '무부하매연측정치2', '무부하매연측정치3', '무부하매연측정치4',
       '무부하매연측정치5', '무부하매연측정치6', '정기정밀', 'vin10', 'vin_year', 'DPF유무'],
      dtype='object')

In [19]:
result['등급'].value_counts(dropna=True)

4    1153813
Name: 등급, dtype: int64

In [20]:
result[result['배출가스인증번호'] == '9MY-KM-14-22'].shape

(39626, 64)

# 4,5 등급 검사 기록 확인

In [5]:
# about 33s
grade = 4
file_name = f'[ODS][G{grade}]등록정보&제원정보(연료수정)(등급컬럼추가)(2022.12.28).csv'
g4 =  pd.read_csv(os.path.join(ods_fold, file_name), low_memory=False)
g4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1511211 entries, 0 to 1511210
Data columns (total 59 columns):
 #   Column        Non-Null Count    Dtype  
---  ------        --------------    -----  
 0   차량관리번호        1511211 non-null  object 
 1   차량등록번호        1511211 non-null  object 
 2   본거지법정동코드      1511211 non-null  int64  
 3   소유자구분         1511211 non-null  object 
 4   차종_등록정보       1511209 non-null  object 
 5   용도            1511211 non-null  object 
 6   현재회원번호        1510372 non-null  object 
 7   차대번호          1511211 non-null  object 
 8   최초등록일자        1511211 non-null  int64  
 9   차량연식          1511211 non-null  int64  
 10  차량제작일자        1342438 non-null  float64
 11  배출가스검사유효일자    1511199 non-null  float64
 12  제원관리번호        1511211 non-null  object 
 13  배출가스인증번호      1387511 non-null  object 
 14  배출가스등급        1511211 non-null  object 
 15  저공해조치YN(미사용)  1511056 non-null  object 
 16  저공해조치종류       189 non-null      float64
 17  저공해조치구조변경YN   1511211 non-n

In [6]:
# about 25s
grade = 5
file_name = f'[ODS][G{grade}]등록정보&제원정보(연료수정)(등급컬럼추가)(2022.12.28).csv'
g5 =  pd.read_csv(os.path.join(ods_fold, file_name), low_memory=False)
g5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1154724 entries, 0 to 1154723
Data columns (total 59 columns):
 #   Column        Non-Null Count    Dtype  
---  ------        --------------    -----  
 0   차량관리번호        1154724 non-null  object 
 1   차량등록번호        1154724 non-null  object 
 2   본거지법정동코드      1154724 non-null  int64  
 3   소유자구분         1154724 non-null  object 
 4   차종_등록정보       1154712 non-null  object 
 5   용도            1154724 non-null  object 
 6   현재회원번호        1146055 non-null  object 
 7   차대번호          1154724 non-null  object 
 8   최초등록일자        1154724 non-null  int64  
 9   차량연식          1154724 non-null  int64  
 10  차량제작일자        959049 non-null   float64
 11  배출가스검사유효일자    1154212 non-null  float64
 12  제원관리번호        1154724 non-null  object 
 13  배출가스인증번호      542935 non-null   object 
 14  배출가스등급        1154724 non-null  object 
 15  저공해조치YN(미사용)  1154650 non-null  object 
 16  저공해조치종류       361633 non-null   float64
 17  저공해조치구조변경YN   1154724 non-n

In [7]:
# about 4m 25s
file_name = '[ODS]정기&정밀검사(최신검사만)(2022.12.28).csv'
tin = pd.read_csv(os.path.join(ods_fold, file_name), low_memory=False)
tin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22044208 entries, 0 to 22044207
Data columns (total 42 columns):
 #   Column     Dtype  
---  ------     -----  
 0   사용연료       object 
 1   주행거리       object 
 2   차명         object 
 3   차량번호       object 
 4   차대번호       object 
 5   차종         object 
 6   차량연식       int64  
 7   엔진형식       object 
 8   검사방법       object 
 9   검사일자       int64  
 10  검사종류       object 
 11  검사판정시각     object 
 12  검사판정       object 
 13  산소값        float64
 14  이산화탄소값     float64
 15  무부하매연판정1   object 
 16  무부하매연판정2   object 
 17  무부하매연판정3   object 
 18  무부하매연판정4   object 
 19  무부하매연판정5   object 
 20  무부하매연판정6   object 
 21  무부하매연허용치1  float64
 22  무부하매연허용치2  float64
 23  무부하매연허용치3  float64
 24  무부하매연허용치4  float64
 25  무부하매연허용치5  float64
 26  무부하매연허용치6  float64
 27  무부하매연측정치1  float64
 28  무부하매연측정치2  float64
 29  무부하매연측정치3  float64
 30  무부하매연측정치4  float64
 31  무부하매연측정치5  float64
 32  무부하매연측정치6  float64
 33  차량용도       object 
 34  최대출력허용치    float

In [8]:
tin.columns

Index(['사용연료', '주행거리', '차명', '차량번호', '차대번호', '차종', '차량연식', '엔진형식', '검사방법',
       '검사일자', '검사종류', '검사판정시각', '검사판정', '산소값', '이산화탄소값', '무부하매연판정1',
       '무부하매연판정2', '무부하매연판정3', '무부하매연판정4', '무부하매연판정5', '무부하매연판정6', '무부하매연허용치1',
       '무부하매연허용치2', '무부하매연허용치3', '무부하매연허용치4', '무부하매연허용치5', '무부하매연허용치6',
       '무부하매연측정치1', '무부하매연측정치2', '무부하매연측정치3', '무부하매연측정치4', '무부하매연측정치5',
       '무부하매연측정치6', '차량용도', '최대출력허용치', '최대출력측정값', '검사접수번호', '검사소명', '재검사기간',
       '정기정밀', '검사 검사소코드', '검사유효기간'],
      dtype='object')

## 최근 3년 검사 데이터 추출

In [9]:
tin['검사일자'].describe()

count   22044208.00
mean    20213557.70
std         8679.78
min     20190102.00
25%     20210427.00
50%     20211222.00
75%     20220614.00
max     20230107.00
Name: 검사일자, dtype: float64

In [10]:
tin1 = tin[(tin['검사일자'] >= 20200101) & (tin['검사일자'] <= 20221231)]
tin1.shape

(20547872, 42)

In [11]:
tin1['검사일자'].describe()

count   20547872.00
mean    20214858.24
std         6580.17
min     20200102.00
25%     20210611.00
50%     20220113.00
75%     20220620.00
max     20221231.00
Name: 검사일자, dtype: float64

In [12]:
g4['연료'].value_counts(dropna=False)

경유             1152694
휘발유             333822
LPG(액화석유가스)      24692
무동력                  1
CNG(압축천연가스)          1
알코올                  1
Name: 연료, dtype: int64

In [13]:
g5['연료'].value_counts(dropna=False)

경유             1124189
휘발유              30093
LPG(액화석유가스)        431
CNG(압축천연가스)          5
무동력                  5
알코올                  1
Name: 연료, dtype: int64

In [14]:
g4.shape

(1511211, 59)

In [15]:
g4 = g4.sort_values(['최초등록일자', '배출가스검사유효일자'], ascending=[False, False]).drop_duplicates('차대번호').reset_index(drop=True)
g4.shape

(1511211, 59)

In [16]:
g5.shape

(1154724, 59)

In [17]:
g5 = g5.sort_values(['최초등록일자', '배출가스검사유효일자'], ascending=[False, False]).drop_duplicates('차대번호').reset_index(drop=True)
g5.shape

(1154724, 59)

In [18]:
# about 47s
g4_tin = g4.merge(tin1, on='차대번호', how='left')
g4_tin.shape

(1511211, 100)

In [19]:
# about 43s
g5_tin = g5.merge(tin1, on='차대번호', how='left')
g5_tin.shape

(1154724, 100)

In [20]:
g4_tin['검사방법'].unique()

array([nan, '부하검사(KD-147)', '부하검사(LUG DOWN)', '무부하검사(급가속)',
       '부하검사(ASM-Idling)', '무부하검사(TSI)', '무부하검사(정지가동)'], dtype=object)

In [21]:
g4_tin['검사종류'].unique()

array([nan, '2부재검사(종합)', '종합검사(경과)', '종합검사', '정기검사', '정기(경과)검사',
       '재검사(2부재검사)', '재검사(1부재검사)', '1부재검사(종합)'], dtype=object)

In [22]:
g5_tin['검사방법'].unique()

array([nan, '부하검사(KD-147)', '무부하검사(급가속)', '부하검사(LUG DOWN)', '무부하검사(TSI)',
       '부하검사(ASM-Idling)', '무부하검사(정지가동)'], dtype=object)

In [23]:
g5_tin['검사종류'].unique()

array([nan, '종합검사', '2부재검사(종합)', '정기검사', '종합검사(경과)', '재검사(2부재검사)',
       '재검사(1부재검사)', '정기(경과)검사', '1부재검사(종합)'], dtype=object)

In [24]:
view_cols = ['검사방법', '검사일자', '검사종류', '검사판정시각', '검사판정', 
'무부하매연판정1', '무부하매연측정치1',
'무부하매연판정2', '무부하매연측정치2',
'무부하매연판정3', '무부하매연측정치3',
'무부하매연판정4', '무부하매연측정치4',
'무부하매연판정5', '무부하매연측정치5',
'무부하매연판정6', '무부하매연측정치6',]

In [25]:
g4_tin[g4_tin['연료'] == '알코올'].reset_index(drop=True)[view_cols].isnull().sum().reset_index()

index  0
0        검사방법  0
1        검사일자  0
2        검사종류  0
3      검사판정시각  0
4        검사판정  0
5    무부하매연판정1  0
6   무부하매연측정치1  0
7    무부하매연판정2  0
8   무부하매연측정치2  0
9    무부하매연판정3  0
10  무부하매연측정치3  0
11   무부하매연판정4  0
12  무부하매연측정치4  0
13   무부하매연판정5  0
14  무부하매연측정치5  0
15   무부하매연판정6  0
16  무부하매연측정치6  0

In [26]:
g4_miss = pd.DataFrame({'컬럼명':view_cols})
for one in g4_tin['연료'].unique():
    temp = g4_tin[g4_tin['연료'] == one].reset_index(drop=True)[view_cols].isnull().sum().reset_index()
    temp.columns = ['컬럼명', f'4등급_{one}']
    g4_miss = g4_miss.merge(temp, on='컬럼명', how='left')

In [27]:
g4_miss

컬럼명   4등급_경유  4등급_휘발유  4등급_무동력  4등급_LPG(액화석유가스)  4등급_CNG(압축천연가스)  \
0        검사방법    44049   276732        0            20380                0   
1        검사일자    44049   276732        0            20380                0   
2        검사종류    44049   276732        0            20380                0   
3      검사판정시각    52626   277303        0            20425                0   
4        검사판정    44049   276732        0            20380                0   
5    무부하매연판정1    52631   277835        1            20478                0   
6   무부하매연측정치1    52626   277835        1            20478                0   
7    무부하매연판정2  1108844   277856        1            20478                1   
8   무부하매연측정치2   794728   277846        1            20478                1   
9    무부하매연판정3  1109724   277856        1            20478                1   
10  무부하매연측정치3   829071   277848        1            20478                1   
11   무부하매연판정4  1109726   278331        1            20658                1   
12  무부하매연측정치4   829073   278321        1            20658                1   
13   무부하매연판정5  1109726   278331        1            20658                1   
14  무부하매연측정치5   829073   278321        1            20658                1   
15   무부하매연판정6  1152689   278331        1            20658                1   
16  무부하매연측정치6   860557   278321        1            20658                1   

    4등급_알코올  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         0  
9         0  
10        0  
11        0  
12        0  
13        0  
14        0  
15        0  
16        0

In [28]:
g5_miss = pd.DataFrame({'컬럼명':view_cols})
for one in g5_tin['연료'].unique():
    temp = g5_tin[g5_tin['연료'] == one].reset_index(drop=True)[view_cols].isnull().sum().reset_index()
    temp.columns = ['컬럼명', f'5등급_{one}']
    g5_miss = g5_miss.merge(temp, on='컬럼명', how='left')

In [29]:
g5_miss

컬럼명   5등급_경유  5등급_휘발유  5등급_CNG(압축천연가스)  5등급_LPG(액화석유가스)  5등급_무동력  \
0        검사방법   417784    29714                3              428        1   
1        검사일자   417784    29714                3              428        1   
2        검사종류   417784    29714                3              428        1   
3      검사판정시각   423735    29718                3              428        1   
4        검사판정   417784    29714                3              428        1   
5    무부하매연판정1   423944    29725                3              428        3   
6   무부하매연측정치1   423935    29725                3              428        3   
7    무부하매연판정2  1017451    29736                3              428        4   
8   무부하매연측정치2   890190    29731                3              428        4   
9    무부하매연판정3  1017777    29736                3              428        4   
10  무부하매연측정치3   909623    29733                3              428        4   
11   무부하매연판정4  1018120    29745                3              430        4   
12  무부하매연측정치4   909965    29737                3              430        4   
13   무부하매연판정5  1018120    29745                3              430        4   
14  무부하매연측정치5   909965    29737                3              430        4   
15   무부하매연판정6  1115337    29745                5              430        5   
16  무부하매연측정치6   982786    29737                4              430        5   

    5등급_알코올  
0         1  
1         1  
2         1  
3         1  
4         1  
5         1  
6         1  
7         1  
8         1  
9         1  
10        1  
11        1  
12        1  
13        1  
14        1  
15        1  
16        1

In [30]:
g45_miss = g4_miss.merge(g5_miss, on='컬럼명', how='left')
g45_miss

컬럼명   4등급_경유  4등급_휘발유  4등급_무동력  4등급_LPG(액화석유가스)  4등급_CNG(압축천연가스)  \
0        검사방법    44049   276732        0            20380                0   
1        검사일자    44049   276732        0            20380                0   
2        검사종류    44049   276732        0            20380                0   
3      검사판정시각    52626   277303        0            20425                0   
4        검사판정    44049   276732        0            20380                0   
5    무부하매연판정1    52631   277835        1            20478                0   
6   무부하매연측정치1    52626   277835        1            20478                0   
7    무부하매연판정2  1108844   277856        1            20478                1   
8   무부하매연측정치2   794728   277846        1            20478                1   
9    무부하매연판정3  1109724   277856        1            20478                1   
10  무부하매연측정치3   829071   277848        1            20478                1   
11   무부하매연판정4  1109726   278331        1            20658                1   
12  무부하매연측정치4   829073   278321        1            20658                1   
13   무부하매연판정5  1109726   278331        1            20658                1   
14  무부하매연측정치5   829073   278321        1            20658                1   
15   무부하매연판정6  1152689   278331        1            20658                1   
16  무부하매연측정치6   860557   278321        1            20658                1   

    4등급_알코올   5등급_경유  5등급_휘발유  5등급_CNG(압축천연가스)  5등급_LPG(액화석유가스)  5등급_무동력  \
0         0   417784    29714                3              428        1   
1         0   417784    29714                3              428        1   
2         0   417784    29714                3              428        1   
3         0   423735    29718                3              428        1   
4         0   417784    29714                3              428        1   
5         0   423944    29725                3              428        3   
6         0   423935    29725                3              428        3   
7         0  1017451    29736                3              428        4   
8         0   890190    29731                3              428        4   
9         0  1017777    29736                3              428        4   
10        0   909623    29733                3              428        4   
11        0  1018120    29745                3              430        4   
12        0   909965    29737                3              430        4   
13        0  1018120    29745                3              430        4   
14        0   909965    29737                3              430        4   
15        0  1115337    29745                5              430        5   
16        0   982786    29737                4              430        5   

    5등급_알코올  
0         1  
1         1  
2         1  
3         1  
4         1  
5         1  
6         1  
7         1  
8         1  
9         1  
10        1  
11        1  
12        1  
13        1  
14        1  
15        1  
16        1

In [31]:
today_date = datetime.today().strftime("%Y.%m.%d_%p.%H.%M.%S")
today_date

'2023.02.22_PM.21.22.39'

In [32]:
g45_miss.to_excel(f'analysis2/4_5등급_검사_결측치_{today_date}.xlsx', index=False)

# 코드 마지막