# 정기검사

# Library

In [2]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import re

In [11]:
col = pd.read_excel('data/220819_정기검사_컬럼명.xlsx')
col.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col     62 non-null     object
dtypes: object(1)
memory usage: 624.0+ bytes


In [12]:
col['col']

0        검사소명
1      정기검사일자
2        검사종류
3      검사접수번호
4      통합접수번호
       ...   
57      관능검사원
58    배출가스검사원
59      책임검사원
60    검사 판정시간
61     자료구분코드
Name: col, Length: 62, dtype: object

In [13]:
df = pd.read_table('data/220819_정기검사.txt', names=col['col'], encoding='cp949')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 796614 entries, 0 to 796613
Data columns (total 62 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   검사소명          796614 non-null  object 
 1   정기검사일자        796614 non-null  int64  
 2   검사종류          796614 non-null  object 
 3   검사접수번호        796614 non-null  object 
 4   통합접수번호        796614 non-null  object 
 5   차량번호          796614 non-null  object 
 6   차대번호          796614 non-null  object 
 7   차량형식번호        796614 non-null  object 
 8   차명            796614 non-null  object 
 9   차종            796614 non-null  object 
 10  차량용도          796614 non-null  object 
 11  차량연식          796614 non-null  int64  
 12  차량연료          787770 non-null  object 
 13  주행거리          795049 non-null  float64
 14  차량길이          796614 non-null  int64  
 15  차량너비          796614 non-null  int64  
 16  차량높이          796614 non-null  int64  
 17  엔진형식          793439 non-null  object 
 18  배기량 

In [14]:
df.columns

Index(['검사소명', '정기검사일자', '검사종류', '검사접수번호', '통합접수번호', '차량번호', '차대번호', '차량형식번호',
       '차명', '차종', '차량용도', '차량연식', '차량연료', '주행거리', '차량길이', '차량너비', '차량높이',
       '엔진형식', '배기량', '엔진출력', '차량중량', '총중량', '정원', '비고', '최초등록일자', '제작일자',
       '검사전 유효기간 만료일', '관능검사판정', '관능부적합항목', '검사방법', '무부하매연측정치1', '무부하매연허용치1',
       '무부하매연판정1', '무부하매연측정치2', '무부하매연허용치2', '무부하매연판정2', '무부하매연측정치3',
       '무부하매연허용치3', '무부하매연판정3', '무부하매연측정치4', '무부하매연허용치4', '무부하매연판정4',
       '무부하매연측정치5', '무부하매연허용치5', '무부하매연판정5', '무부하매연측정치6', '무부하매연허용치6',
       '무부하매연판정6', '이산화탄소값', '최대출력허용치', '최대출력측정값', '산소값', '공기온도', '공기압력',
       '검사판정', '재검사기간', '검사후 갱신유효기간', '관능검사원', '배출가스검사원', '책임검사원', '검사 판정시간',
       '자료구분코드'],
      dtype='object')

In [15]:
# csv 출력
df.to_csv('data/220819_정기검사.csv', encoding='cp949', index=False)
# 24.2s

In [16]:
info_df = df.isnull().sum().reset_index()
info_df.head()

index  0
0    검사소명  0
1  정기검사일자  0
2    검사종류  0
3  검사접수번호  0
4  통합접수번호  0

# 데이터 로드

In [17]:
df = pd.read_csv('data/220819_정기검사.csv', encoding='cp949')

## 기본 확인

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 796614 entries, 0 to 796613
Data columns (total 62 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   검사소명          796614 non-null  object 
 1   정기검사일자        796614 non-null  int64  
 2   검사종류          796614 non-null  object 
 3   검사접수번호        796614 non-null  object 
 4   통합접수번호        796614 non-null  object 
 5   차량번호          796614 non-null  object 
 6   차대번호          796614 non-null  object 
 7   차량형식번호        796614 non-null  object 
 8   차명            796614 non-null  object 
 9   차종            796614 non-null  object 
 10  차량용도          796614 non-null  object 
 11  차량연식          796614 non-null  int64  
 12  차량연료          787770 non-null  object 
 13  주행거리          795049 non-null  float64
 14  차량길이          796614 non-null  int64  
 15  차량너비          796614 non-null  int64  
 16  차량높이          796614 non-null  int64  
 17  엔진형식          793439 non-null  object 
 18  배기량 

In [19]:
# null 값 있는 컬럼
# 12	차량연료	8844
# 13	주행거리	1565
# 17	엔진형식	3175
# 18	배기량	7821
# 20	차량중량	1
# 22	정원	3
# 23	비고	796614
# 25	제작일자	1925
# 27	관능검사판정	796614
# 28	관능부적합항목	796614
# 30	무부하매연측정치1	74995
# 31	무부하매연허용치1	74995
# 32	무부하매연판정1	74995
# 33	무부하매연측정치2	527137
# 34	무부하매연허용치2	527137
# 35	무부하매연판정2	527137
# 36	무부하매연측정치3	527137
# 37	무부하매연허용치3	527139
# 38	무부하매연판정3	527139
# 39	무부하매연측정치4	579474
# 40	무부하매연허용치4	579474
# 41	무부하매연판정4	579474
# 42	무부하매연측정치5	579474
# 43	무부하매연허용치5	579474
# 44	무부하매연판정5	579474
# 45	무부하매연측정치6	579474
# 46	무부하매연허용치6	579474
# 47	무부하매연판정6	579474
# 48	이산화탄소값	527893
# 49	최대출력허용치	796614
# 50	최대출력측정값	796614
# 51	산소값	567647
# 52	공기온도	796614
# 53	공기압력	796614
# 57	관능검사원	56836
# 58	배출가스검사원	58903
# 59	책임검사원	53088

In [20]:
info_df[5:15]

index     0
5     차량번호     0
6     차대번호     0
7   차량형식번호     0
8       차명     0
9       차종     0
10    차량용도     0
11    차량연식     0
12    차량연료  8844
13    주행거리  1565
14    차량길이     0

In [21]:
info_df[15:25]

index       0
15    차량너비       0
16    차량높이       0
17    엔진형식    3175
18     배기량    7821
19    엔진출력       0
20    차량중량       1
21     총중량       0
22      정원       3
23      비고  796614
24  최초등록일자       0

In [22]:
info_df[25:35]

index       0
25          제작일자    1925
26  검사전 유효기간 만료일       0
27        관능검사판정  796614
28       관능부적합항목  796614
29          검사방법       0
30     무부하매연측정치1   74995
31     무부하매연허용치1   74995
32      무부하매연판정1   74995
33     무부하매연측정치2  527137
34     무부하매연허용치2  527137

In [23]:
info_df[35:45]

index       0
35   무부하매연판정2  527137
36  무부하매연측정치3  527137
37  무부하매연허용치3  527139
38   무부하매연판정3  527139
39  무부하매연측정치4  579474
40  무부하매연허용치4  579474
41   무부하매연판정4  579474
42  무부하매연측정치5  579474
43  무부하매연허용치5  579474
44   무부하매연판정5  579474

In [24]:
info_df[45:55]

index       0
45  무부하매연측정치6  579474
46  무부하매연허용치6  579474
47   무부하매연판정6  579474
48     이산화탄소값  527893
49    최대출력허용치  796614
50    최대출력측정값  796614
51        산소값  567647
52       공기온도  796614
53       공기압력  796614
54       검사판정       0

In [25]:
info_df[55:]

index      0
55       재검사기간      0
56  검사후 갱신유효기간      0
57       관능검사원  56836
58     배출가스검사원  58903
59       책임검사원  53088
60     검사 판정시간      0
61      자료구분코드      0

In [26]:
info_df[info_df[0] != 0]

index       0
12       차량연료    8844
13       주행거리    1565
17       엔진형식    3175
18        배기량    7821
20       차량중량       1
22         정원       3
23         비고  796614
25       제작일자    1925
27     관능검사판정  796614
28    관능부적합항목  796614
30  무부하매연측정치1   74995
31  무부하매연허용치1   74995
32   무부하매연판정1   74995
33  무부하매연측정치2  527137
34  무부하매연허용치2  527137
35   무부하매연판정2  527137
36  무부하매연측정치3  527137
37  무부하매연허용치3  527139
38   무부하매연판정3  527139
39  무부하매연측정치4  579474
40  무부하매연허용치4  579474
41   무부하매연판정4  579474
42  무부하매연측정치5  579474
43  무부하매연허용치5  579474
44   무부하매연판정5  579474
45  무부하매연측정치6  579474
46  무부하매연허용치6  579474
47   무부하매연판정6  579474
48     이산화탄소값  527893
49    최대출력허용치  796614
50    최대출력측정값  796614
51        산소값  567647
52       공기온도  796614
53       공기압력  796614
57      관능검사원   56836
58    배출가스검사원   58903
59      책임검사원   53088

## 0\. 검사소명

In [27]:
df.iloc[:, 0].isnull().sum()

0

In [28]:
df.iloc[:, 0].unique()

array(['의정부자동차검사소', '경주자동차검사소', '구미자동차검사소', ..., '(주)베스트원종합정비',
       '평화탑자동차정비㈜', '서울공업사'], dtype=object)

In [29]:
df.iloc[:, 0].value_counts()

춘천자동차검사소               5544
성산자동차검사소               4882
제주자동차검사소               4767
원주자동차검사소               4619
강남자동차검사소               4130
                       ... 
TS모바일자동차검사소(대형)           1
동일자동차공업(주)-용인시            1
서군위현대서비스                  1
테스트_명원기업                  1
안산출장_동안산서비스기아오토큐(주)       1
Name: 검사소명, Length: 1904, dtype: int64

## 1\. 정기검사일자 

In [30]:
df.iloc[:, 1].isnull().sum()

0

In [31]:
df.iloc[:5, 1]

0    20220630
1    20220630
2    20220630
3    20220630
4    20220630
Name: 정기검사일자, dtype: int64

## 2\. 검사종류 

In [32]:
df.iloc[:, 2].isnull().sum()

0

In [33]:
df.iloc[:5, 2]

0    재검사(1부재검사)
1    재검사(1부재검사)
2    재검사(1부재검사)
3    재검사(1부재검사)
4    재검사(1부재검사)
Name: 검사종류, dtype: object

## 3\. 검사접수번호 

In [34]:
df.iloc[:, 3].isnull().sum()

0

In [35]:
df.iloc[:5, 3]

0    41402022063000832
1    47802022063000662
2    47402022063000442
3    45602022063000192
4    118c2022063000672
Name: 검사접수번호, dtype: object

## 4\. 통합접수번호 

In [36]:
df.iloc[:, 4].isnull().sum()

0

In [37]:
df.iloc[:5, 4]

0    41402022063000831
1    47802022063000651
2    47402022063000441
3    45602022063000191
4    118c2022063000671
Name: 통합접수번호, dtype: object

## 5\. 차량번호 

In [38]:
df.iloc[:, 5].isnull().sum()

0

In [39]:
df.iloc[:5, 5]

0    서울31자5948
1      70두1683
2      58수6175
3     721루3838
4    서울32사1214
Name: 차량번호, dtype: object

## 6\. 차대번호 

In [40]:
df.iloc[:5, 6]

0    KMHF341NBLA368601
1    KMJWA37KAEU613836
2    KMHS581BBKU058970
3    KNHMB76138S208448
4    KMHK281GFKU047528
Name: 차대번호, dtype: object

In [41]:
df2 = df.copy()

In [42]:
df2.iloc[:, 6].isnull().sum()

0

In [43]:
df2.iloc[:, 6].value_counts()

KNAF141BEKA809682    224
KNAG741BBLA043588    137
KMHLM41ABMU021533    123
KNAG741BBLA043661    100
KMHFF41CBBA040345     11
                    ... 
KMHGM412BJU292442      1
KPBGH2AE1JP026386      1
KMFWBX7KBKU093434      1
KNHMF37ABKS584325      1
KPACA4AN1EP200174      1
Name: 차대번호, Length: 698811, dtype: int64

In [44]:
dup_vin_df = df2.iloc[:, 6].value_counts().reset_index()
dup_vin_df.columns = ['차대번호', '개수']
dup_vin_df.head()

차대번호   개수
0  KNAF141BEKA809682  224
1  KNAG741BBLA043588  137
2  KMHLM41ABMU021533  123
3  KNAG741BBLA043661  100
4  KMHFF41CBBA040345   11

In [45]:
dup_vin_df.shape

(698811, 2)

In [46]:
max(dup_vin_df['개수'])

224

In [47]:
# 중복 차대번호 추출
dup_vin_df2 = dup_vin_df[dup_vin_df['개수'] > 1].reset_index(drop=True)
dup_vin_df2.shape

(94399, 2)

In [48]:
dup_vin_df2['차대번호'].head()

0    KNAF141BEKA809682
1    KNAG741BBLA043588
2    KMHLM41ABMU021533
3    KNAG741BBLA043661
4    KMHFF41CBBA040345
Name: 차대번호, dtype: object

### 차대 번호 정상 확인

In [49]:
# 차대번호 길이 종류 확인
len_vin = []
for i, one in tqdm(enumerate(df2.iloc[:, 6].to_numpy())):
    len_vin.append(len(str(one)))
set(len_vin)

796614it [00:00, 1337355.63it/s]


{11, 12, 13, 14, 15, 16, 17}

In [50]:
df2['VIN_length'] = [ len(one) for one in df2['차대번호'] ]
df2['VIN_length'].unique()

array([17, 11, 12, 13, 16, 15, 14], dtype=int64)

In [51]:
IOQ = []
for one in df2['차대번호']:
    if ('I' in one) or ('O' in one) or ('Q' in one):
        IOQ.append('Y')
    else:
        IOQ.append('N')
df2['IOQ'] = IOQ

In [52]:
df2['IOQ'].unique()

array(['N', 'Y'], dtype=object)

In [53]:
df2.groupby(['VIN_length', 'IOQ'])['차대번호'].count()

VIN_length  IOQ
11          N          91
12          N         538
13          N          16
14          N           3
15          N           7
16          N           6
17          N      795807
            Y         146
Name: 차대번호, dtype: int64

In [54]:
V_I_dict = df2.groupby(['VIN_length', 'IOQ'])['차대번호'].groups

In [55]:
g = df2.groupby(['VIN_length', 'IOQ'], as_index=False)['차대번호'].count()
V_I_df = g.sort_values(['VIN_length', 'IOQ'], ascending=[True, True])
V_I_df

VIN_length IOQ    차대번호
0          11   N      91
1          12   N     538
2          13   N      16
3          14   N       3
4          15   N       7
5          16   N       6
6          17   N  795807
7          17   Y     146

In [56]:
for v in range(10, 18):
    for i in ['N', 'Y']:
        try:
            idx = V_I_dict[(v, i)]
            print(f'[VIN_length : {v}, "IOQ"포함 : {i}]')
            print('예시)')
            print(df2.iloc[idx[:3], 6])
            print()
        except:
            pass

[VIN_length : 11, "IOQ"포함 : N]
예시)
162     10814246108
2266    03814203246
4089    03814206368
Name: 차대번호, dtype: object

[VIN_length : 12, "IOQ"포함 : N]
예시)
1020     319831135221
12218    410234337645
17190    440234212537
Name: 차대번호, dtype: object

[VIN_length : 13, "IOQ"포함 : N]
예시)
29363     469435586357순
31457     469435586357순
120374    419234320947인
Name: 차대번호, dtype: object

[VIN_length : 14, "IOQ"포함 : N]
예시)
230928    CB-42-C-000626
245753    CB-42-C-000626
671675    SL-68-C-035568
Name: 차대번호, dtype: object

[VIN_length : 15, "IOQ"포함 : N]
예시)
118271    48-93-343-00001
249456    41-98-343-98490
519853    26-98-343-04457
Name: 차대번호, dtype: object

[VIN_length : 16, "IOQ"포함 : N]
예시)
84525     44-00-343-10407홍
184587    KN92J5CFD3MZ0001
201504    41-01-343-33584수
Name: 차대번호, dtype: object

[VIN_length : 17, "IOQ"포함 : N]
예시)
0    KMHF341NBLA368601
1    KMJWA37KAEU613836
2    KMHS581BBKU058970
Name: 차대번호, dtype: object

[VIN_length : 17, "IOQ"포함 : Y]
예시)
4091     KR1PVHHXORB100234
105

##### [출력]번호길이, IOQ포함 통계

In [57]:
V_I_df.to_csv('analysis/[정기검사][차대번호]번호길이_IOQ포함_통계.csv', index=False, encoding='cp949')

#### WMI 코드 분류 제작사 통계

In [58]:
wmi = pd.read_excel('data/20190730_WMI CODE.xlsx', sheet_name='WMI CODE')
wmi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   WMI            690 non-null    object 
 1   MF CODE        690 non-null    object 
 2   Identifier     690 non-null    object 
 3   Manufacturer   690 non-null    object 
 4   Country        688 non-null    object 
 5   Vehicle Types  249 non-null    object 
 6   Description    54 non-null     object 
 7   참고             0 non-null      float64
dtypes: float64(1), object(7)
memory usage: 43.2+ KB


In [59]:
df2['차대번호'].head()

0    KMHF341NBLA368601
1    KMJWA37KAEU613836
2    KMHS581BBKU058970
3    KNHMB76138S208448
4    KMHK281GFKU047528
Name: 차대번호, dtype: object

In [60]:
df2['wmi'] = df2['차대번호'].str[:3]

In [61]:
df2['wmi'].head()

0    KMH
1    KMJ
2    KMH
3    KNH
4    KMH
Name: wmi, dtype: object

In [62]:
df2 = df2.merge(wmi, left_on='wmi', right_on='WMI', how='left')
df2[['차대번호', 'wmi', 'WMI']].head()

차대번호  wmi  WMI
0  KMHF341NBLA368601  KMH  KMH
1  KMJWA37KAEU613836  KMJ  KMJ
2  KMHS581BBKU058970  KMH  KMH
3  KNHMB76138S208448  KNH  KNH
4  KMHK281GFKU047528  KMH  KMH

In [63]:
df2.shape

(796614, 73)

In [64]:
df2[['차대번호', 'wmi', 'WMI', 'Manufacturer']].head()

차대번호  wmi  WMI Manufacturer
0  KMHF341NBLA368601  KMH  KMH      Hyundai
1  KMJWA37KAEU613836  KMJ  KMJ      Hyundai
2  KMHS581BBKU058970  KMH  KMH      Hyundai
3  KNHMB76138S208448  KNH  KNH          Kia
4  KMHK281GFKU047528  KMH  KMH      Hyundai

In [65]:
df2.iloc[:, 6].isnull().sum()

0

##### 차대번호 길이 조건 전부 포함

In [66]:
# 총 샘플 수 : 796614

In [67]:
# 차대번호 길이 조건 전부 포함
df2['WMI'].info()

<class 'pandas.core.series.Series'>
Int64Index: 796614 entries, 0 to 796613
Series name: WMI
Non-Null Count   Dtype 
--------------   ----- 
703101 non-null  object
dtypes: object(1)
memory usage: 12.2+ MB


In [68]:
# wmi 코드와 매칭되는 데이터
nor_iden = df2.loc[df2['WMI'].isnull() == False, ['차량번호', '차대번호', 'wmi', 'WMI', 'Identifier']]
nor_iden.head()

차량번호               차대번호  wmi  WMI Identifier
0  서울31자5948  KMHF341NBLA368601  KMH  KMH    Hyundai
1    70두1683  KMJWA37KAEU613836  KMJ  KMJ    Hyundai
2    58수6175  KMHS581BBKU058970  KMH  KMH    Hyundai
3   721루3838  KNHMB76138S208448  KNH  KNH        Kia
4  서울32사1214  KMHK281GFKU047528  KMH  KMH    Hyundai

In [69]:
# WMI 코드와 매칭되는 샘플 수 : 703101
nor_iden.shape

(703101, 5)

In [70]:
# wmi 유니크 개수 : 158
len(nor_iden['wmi'].unique())

158

In [71]:
# 제작사 유니크 개수 : 71
len(nor_iden['Identifier'].unique())

71

In [72]:
# wmi 코드와 매칭 안되는 데이터
error_iden = df2.loc[df2['WMI'].isnull() == True, ['차량번호', '차대번호', 'wmi', 'WMI', 'Identifier']]
error_iden.head()

차량번호               차대번호  wmi  WMI Identifier
13  96라7037  KMCXNS7BP2U608528  KMC  NaN        NaN
14  41나7328  KPBFA2AF14P139901  KPB  NaN        NaN
28  85가5294  KLTBC6AH19K000069  KLT  NaN        NaN
29  32누3490  KPBGA2AE1JP028617  KPB  NaN        NaN
46  05누5796  KPBKJ2AE1GP111063  KPB  NaN        NaN

In [73]:
# wmi 코드 매칭 안되는 샘플 수 : 93513
error_iden.shape

(93513, 5)

In [74]:
len(error_iden['wmi'].unique())

299

###### [출력]오류 wmi코드 예시

In [75]:
error_iden.to_excel('analysis/[정기검사][차대번호]오류_WMI코드_데이터예시.xlsx',index=False, encoding='cp949')

In [76]:
# wmi 코드와 매칭되는 데이터 통계
nor_iden_group = nor_iden.groupby(['Identifier'], as_index=False)['차대번호'].count().sort_values('차대번호', ascending=False)
nor_iden_group

Identifier    차대번호
23          Hyundai  348754
30              Kia  211861
59        SsangYong   29957
52  Renault Samsung   26276
19        GM Daewoo   13591
..              ...     ...
48          Pontiac       2
67    Xingyue Group       1
12          Daimler       1
6              CAMI       1
0        Alfa Romeo       1

[71 rows x 2 columns]

###### [출력]제작사별 통계

In [77]:
nor_iden_group.to_excel('analysis/[정기검사][차대번호]제작사별_통계.xlsx', index=False, encoding='cp949')

##### 차대번호 정상

In [78]:
# - 길이 17자리, IOQ 문자 미포함
# - 차대번호 개수(정상 WMI 코드) : 795807

In [79]:
nor_vin = df2.loc[(df2['VIN_length'] == 17) & (df2['IOQ'] == 'N')]
nor_vin.head()

검사소명    정기검사일자        검사종류             검사접수번호             통합접수번호  \
0       의정부자동차검사소  20220630  재검사(1부재검사)  41402022063000832  41402022063000831   
1        경주자동차검사소  20220630  재검사(1부재검사)  47802022063000662  47802022063000651   
2        구미자동차검사소  20220630  재검사(1부재검사)  47402022063000442  47402022063000441   
3        정읍자동차검사소  20220630  재검사(1부재검사)  45602022063000192  45602022063000191   
4  구로출장_봉천자동차정비공업  20220630  재검사(1부재검사)  118c2022063000672  118c2022063000671   

        차량번호               차대번호             차량형식번호                       차명  \
0  서울31자5948  KMHF341NBLA368601  A0810012000201319            그랜저(GRANDEUR)   
1    70두1683  KMJWA37KAEU613836  A0810007404712213   그랜드 스타렉스(GRAND STAREX)   
2    58수6175  KMHS581BBKU058970  A0810011400291218             싼타페(SANTAFE)   
3   721루3838  KNHMB76138S208448  A0110003600422207                  그랜드 카니발   
4  서울32사1214  KMHK281GFKU047528  A0810010900301218  코나 일렉트릭 (KONA ELECTRIC)   

          차종  ... IOQ  wmi  WMI  MF CODE  Identifier  Manufacturer  Country  \
0   승용차일반형대형  ...   N  KMH  KMH     HYUN     Hyundai       Hyundai    Korea   
1   승합차일반형중형  ...   N  KMJ  KMJ     HYUN     Hyundai       Hyundai    Korea   
2  승용차다목적형중형  ...   N  KMH  KMH     HYUN     Hyundai       Hyundai    Korea   
3   승합차일반형중형  ...   N  KNH  KNH      KIA         Kia           Kia    Korea   
4  승용차다목적형중형  ...   N  KMH  KMH     HYUN     Hyundai       Hyundai    Korea   

                       Vehicle Types  Description  참고  
0  Passenger & multi-purpose vehicle          NaN NaN  
1           Commercial vehicle & bus          NaN NaN  
2  Passenger & multi-purpose vehicle          NaN NaN  
3                                Bus          NaN NaN  
4  Passenger & multi-purpose vehicle          NaN NaN  

[5 rows x 73 columns]

In [80]:
nor_vin.shape

(795807, 73)

In [81]:
# wmi 코드와 매칭된 데이터
nor_iden_by_nor_vin = nor_vin.loc[nor_vin['WMI'].isnull() == False]
nor_iden_by_nor_vin.shape

(703060, 73)

In [82]:
# wmi 코드와 매칭안된 데이터
nor_vin.loc[nor_vin['WMI'].isnull() == True].shape

(92747, 73)

In [83]:
# wmi 코드와 매칭된 데이터, 제작사 유니크 값
len(nor_iden_by_nor_vin['Identifier'].unique())

71

In [84]:
# wmi 코드와 매칭된 데이터, wmi 유니크 값
len(nor_iden_by_nor_vin['WMI'].unique())

157

In [85]:
# wmi 코드와 매칭된 데이터 통계
nor_iden_by_nor_vin_group = nor_iden_by_nor_vin.groupby('Identifier', as_index=False)['차대번호'].count().sort_values('차대번호', ascending=False)
nor_iden_by_nor_vin_group

Identifier    차대번호
23          Hyundai  348752
30              Kia  211860
59        SsangYong   29954
52  Renault Samsung   26276
19        GM Daewoo   13589
..              ...     ...
48          Pontiac       2
67    Xingyue Group       1
12          Daimler       1
6              CAMI       1
0        Alfa Romeo       1

[71 rows x 2 columns]

###### [출력]제작사별 통계(정상차대번호)

In [86]:
nor_iden_by_nor_vin_group.to_excel('analysis/[정기검사][차대번호]제작사별_통계(정상차대번호).xlsx', encoding='cp949')

## 7\. 차량형식번호 

In [87]:
df.iloc[:, 7].isnull().sum()

0

In [88]:
df.iloc[:5, 7]

0    A0810012000201319
1    A0810007404712213
2    A0810011400291218
3    A0110003600422207
4    A0810010900301218
Name: 차량형식번호, dtype: object

## 8\. 차명 

In [89]:
df.iloc[:, 8].isnull().sum()

0

In [90]:
df.iloc[:5, 8]

0              그랜저(GRANDEUR)
1     그랜드 스타렉스(GRAND STAREX)
2               싼타페(SANTAFE)
3                    그랜드 카니발
4    코나 일렉트릭 (KONA ELECTRIC)
Name: 차명, dtype: object

## 9\. 차종 

In [91]:
df.iloc[:, 9].isnull().sum()

0

In [92]:
df.iloc[:5, 9]

0     승용차일반형대형
1     승합차일반형중형
2    승용차다목적형중형
3     승합차일반형중형
4    승용차다목적형중형
Name: 차종, dtype: object

In [93]:
df['차종'].unique()

array(['승용차일반형대형', '승합차일반형중형', '승용차다목적형중형', '화물차일반형소형', '화물차특수용도형중형',
       '승용차다목적형대형', '화물차일반형중형', '승용차일반형중형', '승용차일반형경형', '화물차일반형대형',
       '화물차밴형소형', '승용차기타형대형', '화물차특수용도형소형', '화물차덤프형소형', '승용차기타형중형',
       '승합차일반형대형', '승용차겸화물형경형', '화물차일반형경형', '화물차특수용도형대형', '승용차일반형소형',
       '화물차특수용도형경형', '승합차특수형중형', '화물차피견인형적재함형', '화물차피견인형샷시형',
       '화물차피견인형고상형', '화물차피견인형저상형', '화물차밴형경형', '승합차일반형경형', '승용차기타형경형',
       '화물차밴형중형', '특수차특수용도형중형', '화물차덤프형대형', '특수차특수용도형소형', '특수차견인형대형',
       '화물차탱크로리형대형', '화물차덤프형중형', '특수차구난형중형', '특수차특수용도형대형', '화물차탱크로리형중형',
       '특수차구난형소형', '특수차구난형대형', '승합차일반형소형', '승합차특수형경형', '승용차겸화물형대형',
       '승합차특수형대형', '화물차피견인형기타형', '승합차특수형소형', '승용차다목적형소형', '특수차견인형소형',
       '화물차덤프형경형', '특수차특수용도형경형', '화물차밴형대형', '화물차탱크로리형경형', '화물차탱크로리형소형',
       '특수차견인형중형'], dtype=object)

In [94]:
df.loc[df['차종'].str.contains('화물차'), ['검사종류', '제작일자', '차명', '차종', '차량용도', '검사방법']]

검사종류        제작일자             차명          차종 차량용도        검사방법
5       재검사(2부재검사)  20140722.0  포터Ⅱ (PORTERⅡ)    화물차일반형소형  자가용  무부하검사(급가속)
7       재검사(1부재검사)  20190429.0         봉고Ⅲ 1톤    화물차일반형소형  자가용  무부하검사(급가속)
8       재검사(2부재검사)  20140722.0  포터Ⅱ (PORTERⅡ)    화물차일반형소형  자가용  무부하검사(급가속)
13      재검사(2부재검사)  20020721.0   포터초장축수퍼캡냉동탑차  화물차특수용도형중형  자가용  무부하검사(급가속)
16      재검사(1부재검사)  20080523.0          이-마이티    화물차일반형중형  자가용  무부하검사(급가속)
...            ...         ...            ...         ...  ...         ...
796592  재검사(2부재검사)  20061026.0         액티언스포츠    화물차일반형소형  자가용  무부하검사(급가속)
796596  재검사(1부재검사)  20011109.0        석영사료운반차  화물차특수용도형대형  자가용  무부하검사(급가속)
796598  재검사(2부재검사)  20091222.0         봉고Ⅲ 1톤    화물차일반형소형  자가용  무부하검사(급가속)
796601  재검사(1부재검사)  20210504.0     봉고Ⅲ 플러스냉동차  화물차특수용도형소형  영업용  무부하검사(급가속)
796602  재검사(2부재검사)  20210222.0   한국상용6.5톤카고트럭    화물차일반형대형  영업용  무부하검사(급가속)

[273986 rows x 6 columns]

## 10\. 차량용도 

In [95]:
df.iloc[:, 10].isnull().sum()

0

In [96]:
df.iloc[:5, 10]

0    개인택시
1     자가용
2     자가용
3     자가용
4    개인택시
Name: 차량용도, dtype: object

In [97]:
df['차량용도'].unique()

array(['개인택시', '자가용', '영업용', '관용'], dtype=object)

## 11\. 차량연식 

In [98]:
df.iloc[:, 11].isnull().sum()

0

In [99]:
df.iloc[:5, 11]

0    2020
1    2014
2    2019
3    2008
4    2019
Name: 차량연식, dtype: int64

## 12\. 차량연료 

In [100]:
df.iloc[:, 12].isnull().sum()

8844

In [101]:
df.iloc[:5, 12]

0    엘피지
1     경유
2     경유
3     경유
4     전기
Name: 차량연료, dtype: object

In [102]:
df.iloc[:, 12].value_counts()

경유               452065
휘발유(무연)          175488
휘발유               61336
엘피지               57342
하이브리드(휘발유+전기)     19797
전기                15291
CNG                5772
하이브리드(LPG+전기)       276
HE(수소전기)            138
기타연료                115
하이브리드(경유+전기)         77
하이브리드(CNG+전기)        65
LNG                   4
휘발유(유연)               3
태양열                   1
Name: 차량연료, dtype: int64

In [103]:
df.iloc[:, 0].isnull().sum()

0

## 13\. 주행거리 

In [104]:
df.iloc[:, 13].isnull().sum()

1565

In [105]:
df.iloc[:5, 13

]

0    128017.0
1    158871.0
2     81656.0
3    208298.0
4    197829.0
Name: 주행거리, dtype: float64

## 14\. 차량길이

In [106]:
df.iloc[:5, 14]

0    4990
1    5125
2    4770
3    5130
4    4180
Name: 차량길이, dtype: int64

## 15\. 차량너비 

In [107]:
df.iloc[:5, 15]

0    1875
1    1920
2    1890
3    1985
4    1800
Name: 차량너비, dtype: int64

## 16\. 차량높이 

In [108]:
df.iloc[:5, 16]

0    1480
1    1925
2    1680
3    1830
4    1570
Name: 차량높이, dtype: int64

## 17\. 엔진형식 

In [109]:
df.iloc[:5, 17]

0    L6DB
1    D4CB
2    D4HA
3      J3
4    EM16
Name: 엔진형식, dtype: object

## 18\. 배기량 

In [110]:
df.iloc[:5, 18]

0    2999.0
1    2497.0
2    1995.0
3    2902.0
4     180.0
Name: 배기량, dtype: float64

## 19\. 엔진출력 

In [111]:
df.iloc[:5, 19]

0    235/6000
1    140/3800
2    186/4000
3    170/3700
4    150/3800
Name: 엔진출력, dtype: object

## 20\. 차량중량 

In [112]:
df.iloc[:5, 20]

0    1640.0
1    2185.0
2    1810.0
3    2220.0
4    1685.0
Name: 차량중량, dtype: float64

## 21\. 총중량 

In [113]:
df.iloc[:5, 21]

0    1965
1    2965
2    2135
3    2935
4    2010
Name: 총중량, dtype: int64

## 22\. 정원

In [114]:
df.iloc[:5, 22]

0     5.0
1    12.0
2     5.0
3    11.0
4     5.0
Name: 정원, dtype: float64

## 23\. 비고 

In [115]:
df.iloc[:5, 23]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 비고, dtype: float64

In [116]:
df.iloc[:, 23].unique()

array([nan])

## 24\. 최초등록일자 

In [117]:
df.iloc[:5, 24]

0    20200626
1    20131205
2    20180712
3    20071115
4    20190717
Name: 최초등록일자, dtype: int64

## 25\. 제작일자 

In [118]:
df.iloc[:5, 25]

0    20200622.0
1    20131130.0
2    20180703.0
3    20070905.0
4    20190626.0
Name: 제작일자, dtype: float64

In [119]:
df.iloc[:, 25].isnull().sum()

1925

In [120]:
df.loc[df['제작일자'].isnull() == True, ['차대번호', '제작일자']].head()

차대번호  제작일자
456   KMHJF31KPTU334445   NaN
1512  KMHMF11FPSU085571   NaN
2626  KNCSB1125TS703543   NaN
3084  KMFMA19HPSU027208   NaN
3504  KMFLA19JPTC102343   NaN

In [121]:
df.loc[df['제작일자'].isnull() == True, ['차대번호', '제작일자']].shape

(1925, 2)

In [122]:
temp = df.loc[df['제작일자'].isnull() == True, ['차대번호', '제작일자']]

In [123]:
# 제작일자 null 값 샘플 중 차대번호(17자리, IOQ 제외)인 데이터
idx25 = []
for i, one in enumerate(temp['차대번호']):
    if (len(one) == 17) and ('I' not in one) and ('O' not in one) and ('Q' not in one):
        idx25.append(temp.index[i])
len(idx25)

1824

In [124]:
df.loc[idx25, ['차대번호', '차량번호', '차량연식', '최초등록일자', '제작일자', '비고']].head()

차대번호       차량번호  차량연식    최초등록일자  제작일자  비고
456   KMHJF31KPTU334445    23더6026  1996  19960614   NaN NaN
1512  KMHMF11FPSU085571   강원3도5405  1995  19950601   NaN NaN
2626  KNCSB1125TS703543  강원80다2062  1996  19960704   NaN NaN
3084  KMFMA19HPSU027208    96라9641  1995  19950928   NaN NaN
3504  KMFLA19JPTC102343    92무0426  1996  19960216   NaN NaN

In [125]:
df.loc[idx25[0], '차대번호'][9]

'T'

## 26\. 검사전 유효기간 만료일

In [126]:
df.iloc[:5, 26]

0    20220625
1    20220604
2    20220711
3    20220627
4    20220716
Name: 검사전 유효기간 만료일, dtype: int64

## 27\. 관능검사판정

In [127]:
df.iloc[:5, 27]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 관능검사판정, dtype: float64

In [129]:
df.iloc[:5, 27].unique()

array([nan])

## 28\. 관능부적합항목

In [128]:
df.iloc[:5, 28]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 관능부적합항목, dtype: float64

In [130]:
df.iloc[:5, 28].unique()

array([nan])

## 29\. 검사방법

In [131]:
df.iloc[:5, 29]

0    무부하검사(정지가동)
1     무부하검사(급가속)
2     무부하검사(급가속)
3     무부하검사(급가속)
4    무부하검사(정지가동)
Name: 검사방법, dtype: object

In [132]:
df.iloc[:, 29].unique()

array(['무부하검사(정지가동)', '무부하검사(급가속)', '무부하검사(TSI)'], dtype=object)

## 30\. 무부하매연측정치1

In [133]:
df.iloc[:5, 30]

0    NaN
1    0.0
2    0.0
3    0.0
4    NaN
Name: 무부하매연측정치1, dtype: float64

In [184]:
df.iloc[:, 30].unique()

array([     nan, 0.00e+00, 2.00e+00, 1.70e+01, 1.00e+00, 1.20e+01,
       1.00e+01, 1.00e-02, 1.00e-01, 1.20e-01, 5.00e-01, 1.70e-01,
       4.00e-01, 3.00e-02, 1.40e-01, 2.00e-02, 3.00e-01, 2.00e-01,
       3.10e-01, 4.80e-01, 5.40e-01, 3.00e+00, 5.30e+01, 4.30e+01,
       3.30e+01, 2.30e+01, 7.00e+00, 8.00e+00, 5.00e+00, 4.00e+00,
       1.40e+01, 1.10e+01, 9.00e+00, 6.00e-02, 4.00e-02, 7.00e-02,
       5.00e-02, 8.00e-01, 1.50e-01, 1.80e-01, 9.00e-02, 1.60e-01,
       2.10e-01, 2.80e-01, 8.00e-02, 6.00e+01, 3.50e+01, 1.90e-01,
       4.40e-01, 2.00e+01, 2.40e-01, 2.50e-01, 1.10e-01, 4.90e-01,
       5.80e-01, 2.20e-01, 3.90e-01, 4.60e-01, 7.00e-01, 5.30e-01,
       3.00e+01, 2.10e+01, 3.30e-01, 6.90e-01, 6.00e-01, 3.50e-01,
       3.80e-01, 2.80e+01, 1.17e+00, 1.40e+00, 5.10e-01, 9.30e-01,
       6.00e+00, 3.40e+01, 2.70e-01, 5.90e-01, 1.30e-01, 2.90e+01,
       9.00e-01, 5.60e-01, 7.10e-01, 2.20e+01, 7.20e-01, 9.10e-01,
       1.69e+00, 1.90e+00, 5.20e-01, 2.90e-01, 8.50e+01, 2.98e

## 31\. 무부하매연허용치1

In [134]:
df.iloc[:5, 31]

0    NaN
1    0.0
2    0.0
3    0.0
4    NaN
Name: 무부하매연허용치1, dtype: float64

In [185]:
df.iloc[:, 31].unique()

array([ nan,  0. , 25. ,  1. , 15. , 50. , 45. , 60. ,  2.5,  1.2, 10. ,
       20. ,  4.5, 35. , 55. , 40. , 65. , 30. ])

## 32\. 무부하매연판정1

In [136]:
df.iloc[:5, 32]

0    NaN
1      Y
2      Y
3      Y
4    NaN
Name: 무부하매연판정1, dtype: object

In [186]:
df.iloc[:, 32].unique()

array([nan, 'Y', 'N'], dtype=object)

## 33\. 무부하매연측정치2

In [188]:
df.iloc[:5, 33]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 무부하매연측정치2, dtype: float64

In [189]:
df.iloc[:, 33].unique()

array([      nan, 2.000e+00, 2.100e+01, 5.800e+01, 0.000e+00, 1.000e+00,
       4.000e+00, 3.200e+01, 5.000e+00, 2.900e+01, 7.000e+00, 2.200e+01,
       3.400e+01, 1.600e+01, 4.900e+01, 3.000e+00, 6.500e+01, 2.060e+02,
       1.200e+01, 9.000e+00, 3.800e+01, 6.000e+00, 6.800e+01, 1.400e+01,
       1.020e+02, 1.100e+01, 4.200e+01, 6.300e+01, 1.900e+01, 2.000e+01,
       2.800e+01, 1.300e+01, 1.500e+01, 2.600e+01, 1.240e+02, 3.500e+01,
       8.000e+00, 2.440e+02, 7.400e+01, 1.000e+01, 5.000e+01, 6.000e+01,
       6.600e+01, 1.700e+01, 4.400e+01, 1.060e+02, 4.800e+01, 7.500e+01,
       4.000e+01, 7.100e+01, 6.100e+01, 6.010e+02, 1.800e+01, 9.000e+01,
       1.140e+02, 5.200e+01, 1.550e+02, 3.900e+01, 2.400e+01, 1.500e+02,
       3.300e+01, 3.100e+01, 5.700e+01, 2.500e+01, 1.400e+02, 3.000e+01,
       8.200e+01, 7.700e+01, 1.920e+02, 2.190e+02, 1.090e+02, 1.410e+02,
       2.300e+01, 8.100e+01, 1.860e+02, 9.300e+01, 2.700e+01, 1.190e+02,
       9.100e+01, 8.400e+01, 5.400e+01, 4.100e+01, 

## 34\. 무부하매연허용치2

In [139]:
df.iloc[:5, 34]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 무부하매연허용치2, dtype: float64

In [190]:
df.iloc[:, 34].unique()

array([  nan,  150.,  120.,  400.,  220.,    0., 1200.])

## 35\. 무부하매연판정2

In [141]:
df.iloc[:5, 35]

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: 무부하매연판정2, dtype: object

In [191]:
df.iloc[:, 35].unique()

array([nan, 'Y', 'N'], dtype=object)

## 36\. 무부하매연측정치3

In [143]:
df.iloc[:5, 36]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 무부하매연측정치3, dtype: float64

In [192]:
df.iloc[:, 36].unique()

array([ nan, 1.01, 1.22, 1.  , 1.02, 1.06, 0.99, 1.03, 1.05, 1.08, 1.04,
       1.1 , 1.07, 1.09, 0.95, 0.  , 0.94, 0.98, 0.92, 1.24, 1.15, 1.16,
       1.21, 1.13, 1.52, 1.74, 1.48, 1.11, 1.12, 0.97, 1.14, 2.  , 1.18,
       1.37, 0.96, 0.91, 0.93, 1.46, 1.49, 1.32, 1.29, 1.23, 2.5 , 1.2 ,
       1.19, 1.53, 1.5 , 1.63, 1.3 , 0.87, 1.69, 0.88, 1.17, 1.6 , 1.27,
       1.51, 1.25, 1.81, 0.9 , 1.33, 1.31, 1.59, 0.83, 1.28, 1.4 , 1.95,
       0.86, 1.43, 1.83, 1.58, 1.45, 1.26, 1.44, 1.76, 1.38, 1.56, 2.12,
       3.  , 1.66, 0.3 , 1.82, 1.36, 1.35, 2.32, 0.75, 2.47, 1.94, 0.78,
       1.7 , 0.79, 1.85, 1.55, 1.34, 2.44, 1.42, 1.9 , 0.74, 1.75, 1.77,
       1.99, 1.84, 2.07, 1.41, 1.54, 1.39, 0.77, 0.7 , 0.85, 2.08, 0.66,
       0.41, 1.57, 0.5 , 1.67, 1.71, 2.09, 2.05, 2.16, 1.65, 0.81, 1.87,
       2.17, 0.82, 1.64, 0.84, 0.67, 2.34, 0.76, 1.47, 0.63, 1.89, 1.97,
       0.89, 2.26, 1.73, 1.96, 0.51, 0.56, 1.62, 1.78, 1.72, 2.43, 1.88,
       1.61, 1.68, 0.72, 2.18, 0.8 , 0.42, 1.92, 2.

## 37\. 무부하매연허용치3

In [145]:
df.iloc[:5, 37]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 무부하매연허용치3, dtype: float64

In [193]:
df.iloc[:, 37].unique()

array([ nan, 0.1 , 0.  , 0.15, 0.2 ])

## 38\. 무부하매연판정3

In [147]:
df.iloc[:5, 38]

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: 무부하매연판정3, dtype: object

In [194]:
df.iloc[:, 38].unique()

array([nan, 'Y', 'N'], dtype=object)

## 39\. 무부하매연측정치4

In [149]:
df.iloc[:5, 39]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 무부하매연측정치4, dtype: float64

In [195]:
df.iloc[:, 39].unique()

array([  nan,  0.  ,  0.2 ,  0.01,  0.1 ,  0.04,  7.23,  0.07,  0.03,
        0.4 ,  0.15,  0.6 ,  0.06,  0.09,  0.13,  0.3 ,  0.35,  0.17,
        0.8 ,  1.  ,  0.74,  0.21,  0.5 ,  0.7 ,  0.11,  0.43,  0.02,
        0.93,  0.49,  0.05,  0.08,  0.34,  0.29,  0.33,  0.22,  0.84,
        0.9 ,  0.27,  0.25,  0.18,  0.12,  0.39,  0.36,  0.56,  0.69,
        0.14,  0.42,  0.71,  0.24,  0.23,  0.92,  1.3 ,  0.53,  0.59,
        0.37,  0.28,  0.41,  0.46,  0.48,  1.5 ,  0.61,  0.19,  0.51,
        1.47,  0.32,  0.31,  2.7 ,  8.86,  0.44,  0.47,  0.26,  1.12,
        0.68,  1.8 ,  0.73,  0.16,  0.45,  1.99,  0.83,  0.96,  1.2 ,
        0.62,  0.57,  0.63,  0.82,  4.05,  0.55,  1.63,  0.75,  0.66,
        1.56,  2.5 ,  0.65,  6.  ,  0.81,  0.54,  0.38,  0.67,  1.4 ,
        0.91,  1.37,  0.87,  1.6 ,  1.1 ,  1.34,  0.98,  1.85,  1.7 ,
        0.58,  0.79,  1.14,  0.86,  4.2 ,  0.78,  7.86,  0.52,  4.7 ,
        5.04,  2.  ,  1.65,  0.94,  0.95,  2.3 ,  0.97,  1.02,  0.72,
        0.85,  8.8 ,

## 40\. 무부하매연허용치4

In [151]:
df.iloc[:5, 40]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 무부하매연허용치4, dtype: float64

In [196]:
df.iloc[:, 40].unique()

array([nan, 1. , 1.2, 2.5, 4.5, 0. ])

## 41\. 무부하매연판정4

In [153]:
df.iloc[:5, 41]

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: 무부하매연판정4, dtype: object

In [197]:
df.iloc[:, 41].unique()

array([nan, 'Y', 'N'], dtype=object)

## 42\. 무부하매연측정치5

In [155]:
df.iloc[:5, 42]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 무부하매연측정치5, dtype: float64

In [198]:
df.iloc[:, 42].unique()

array([      nan, 5.000e+00, 0.000e+00, 3.000e+00, 1.000e+00, 7.000e+00,
       2.300e+01, 2.200e+01, 2.900e+01, 2.000e+00, 6.000e+00, 3.100e+01,
       5.830e+02, 3.500e+01, 1.200e+01, 5.300e+01, 9.000e+00, 2.130e+02,
       1.000e+01, 1.900e+01, 4.000e+00, 2.100e+01, 2.400e+01, 6.100e+01,
       1.700e+01, 1.400e+01, 1.100e+01, 5.600e+01, 4.000e+01, 1.500e+01,
       3.400e+01, 5.900e+01, 6.500e+01, 4.300e+01, 2.600e+01, 1.180e+02,
       8.000e+00, 1.800e+01, 4.100e+01, 2.000e+01, 1.190e+02, 1.300e+01,
       6.600e+01, 1.600e+01, 3.000e+01, 7.900e+01, 1.070e+02, 1.100e+02,
       1.340e+02, 5.100e+01, 4.400e+01, 9.600e+01, 3.700e+01, 1.020e+02,
       6.400e+01, 3.600e+01, 3.300e+01, 8.100e+01, 1.770e+02, 1.260e+02,
       2.500e+01, 5.400e+01, 8.600e+01, 4.900e+01, 7.000e+01, 6.700e+01,
       5.800e+01, 4.600e+01, 3.800e+01, 6.200e+01, 6.300e+01, 2.700e+01,
       7.100e+01, 1.000e+02, 3.900e+01, 1.860e+02, 7.700e+01, 6.000e+01,
       6.800e+01, 1.440e+02, 1.834e+03, 7.500e+01, 

## 43\. 무부하매연허용치5

In [157]:
df.iloc[:5, 42]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 무부하매연측정치5, dtype: float64

In [199]:
df.iloc[:, 42].unique()

array([      nan, 5.000e+00, 0.000e+00, 3.000e+00, 1.000e+00, 7.000e+00,
       2.300e+01, 2.200e+01, 2.900e+01, 2.000e+00, 6.000e+00, 3.100e+01,
       5.830e+02, 3.500e+01, 1.200e+01, 5.300e+01, 9.000e+00, 2.130e+02,
       1.000e+01, 1.900e+01, 4.000e+00, 2.100e+01, 2.400e+01, 6.100e+01,
       1.700e+01, 1.400e+01, 1.100e+01, 5.600e+01, 4.000e+01, 1.500e+01,
       3.400e+01, 5.900e+01, 6.500e+01, 4.300e+01, 2.600e+01, 1.180e+02,
       8.000e+00, 1.800e+01, 4.100e+01, 2.000e+01, 1.190e+02, 1.300e+01,
       6.600e+01, 1.600e+01, 3.000e+01, 7.900e+01, 1.070e+02, 1.100e+02,
       1.340e+02, 5.100e+01, 4.400e+01, 9.600e+01, 3.700e+01, 1.020e+02,
       6.400e+01, 3.600e+01, 3.300e+01, 8.100e+01, 1.770e+02, 1.260e+02,
       2.500e+01, 5.400e+01, 8.600e+01, 4.900e+01, 7.000e+01, 6.700e+01,
       5.800e+01, 4.600e+01, 3.800e+01, 6.200e+01, 6.300e+01, 2.700e+01,
       7.100e+01, 1.000e+02, 3.900e+01, 1.860e+02, 7.700e+01, 6.000e+01,
       6.800e+01, 1.440e+02, 1.834e+03, 7.500e+01, 

## 44\. 무부하매연판정5

In [159]:
df.iloc[:5, 44]

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: 무부하매연판정5, dtype: object

In [200]:
df.iloc[:, 44].unique()

array([nan, 'Y', 'N'], dtype=object)

## 45\. 무부하매연측정치6

In [161]:
df.iloc[:5, 45]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 무부하매연측정치6, dtype: float64

In [201]:
df.iloc[:, 45].unique()

array([ nan, 0.99, 1.  , 1.01, 1.03, 1.02, 0.79, 1.05, 1.07, 0.98, 1.1 ,
       1.04, 1.06, 0.95, 1.08, 0.97, 0.91, 0.9 , 1.09, 0.96, 0.92, 1.52,
       1.17, 1.18, 0.94, 1.12, 0.83, 1.31, 1.11, 0.93, 1.64, 1.15, 2.49,
       0.8 , 1.19, 1.16, 2.5 , 1.36, 1.14, 1.29, 1.8 , 0.5 , 1.25, 1.2 ,
       1.53, 0.88, 2.44, 1.13, 0.74, 0.89, 0.86, 1.32, 0.75, 1.23, 0.76,
       0.81, 0.68, 0.82, 1.22, 0.69, 2.03, 1.4 , 0.7 , 1.26, 0.84, 1.97,
       1.99, 1.67, 1.87, 1.69, 0.78, 1.28, 1.6 , 1.3 , 1.46, 1.43, 1.45,
       1.21, 1.33, 0.52, 0.72, 1.62, 1.35, 2.07, 0.85, 1.41, 1.56, 1.68,
       1.95, 1.65, 0.73, 1.24, 0.57, 2.62, 3.  , 0.87, 1.27, 0.77, 2.53,
       1.51, 1.34, 1.93, 1.37, 1.42, 1.38, 2.99, 2.  , 1.54, 1.39, 0.63,
       2.59, 2.08, 2.36, 2.15])

## 46\. 무부하매연허용치6

In [163]:
df.iloc[:5, 46]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 무부하매연허용치6, dtype: float64

In [202]:
df.iloc[:, 46].unique()

array([ nan, 0.1 , 0.15, 0.2 , 0.  ])

## 47\. 무부하매연판정6

In [165]:
df.iloc[:5, 47]

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: 무부하매연판정6, dtype: object

In [203]:
df.iloc[:, 47].unique()

array([nan, 'Y', 'N'], dtype=object)

## 48\. 이산화탄소값

In [167]:
df.iloc[:5, 48]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 이산화탄소값, dtype: float64

In [204]:
df.iloc[:, 48].unique()

array([  nan, 14.2 , 11.8 , ...,  0.73,  4.86,  6.55])

## 49\. 최대출력허용치

In [169]:
df.iloc[:5, 49]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 최대출력허용치, dtype: float64

In [205]:
df.iloc[:, 49].unique()

array([nan])

## 50\. 최대출력측정값

In [171]:
df.iloc[:5, 50]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 최대출력측정값, dtype: float64

In [206]:
df.iloc[:, 50].unique()

array([nan])

## 51\. 산소값

In [173]:
df.iloc[:5, 51]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 산소값, dtype: float64

In [207]:
df.iloc[:, 51].unique()

array([  nan,  0.2 ,  3.9 , ...,  3.51, 19.44, 18.84])

## 52\. 공기온도

In [175]:
df.iloc[:5, 52]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 공기온도, dtype: float64

In [208]:
df.iloc[:, 52].unique()

array([nan])

## 53\. 공기압력

In [177]:
df.iloc[:5, 53]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: 공기압력, dtype: float64

In [209]:
df.iloc[:, 53].unique()

array([nan])

## 54\. 검사판정

In [179]:
df.iloc[:5, 54]

0    Y
1    Y
2    Y
3    N
4    Y
Name: 검사판정, dtype: object

In [210]:
df.iloc[:, 54].unique()

array(['Y', 'N'], dtype=object)

## 55\. 재검사기간

In [148]:
df.iloc[:5, 55]

0    20220630~20220805
1    20220630~20220715
2    20220630~20220821
3    20220630~20220807
4    20220630~20220826
Name: 재검사기간, dtype: object

## 56\. 검사후 갱신유효기간

In [149]:
df.iloc[:5, 56]

0    20220626~20230625
1    20220605~20221204
2    20220712~20240711
3    20220628~20221227
4    20220717~20230716
Name: 검사후 갱신유효기간, dtype: object

## 57\. 관능검사원

In [150]:
df.iloc[:5, 57]

0    최지훈
1    김영수
2    허진우
3    정광영
4    김경호
Name: 관능검사원, dtype: object

## 58\. 배출가스검사원

In [151]:
df.iloc[:5, 58]

0    장정우
1    김동현
2    이건호
3    정광영
4    이기태
Name: 배출가스검사원, dtype: object

## 59\. 책임검사원

In [152]:
df.iloc[:5, 59]

0    박기열
1    이준석
2    박주하
3    김동윤
4    이광구
Name: 책임검사원, dtype: object

## 60\. 검사 판정시간

In [153]:
df.iloc[:5, 60]

0    20220701 11:08:49
1    20220701 09:26:26
2    20220701 15:05:16
3    20220701 16:57:36
4    20220701 15:53:50
Name: 검사 판정시간, dtype: object

## 61\. 자료구분코드

In [181]:
df.iloc[:5, 61]

0    D
1    D
2    D
3    D
4    D
Name: 자료구분코드, dtype: object

In [211]:
df.iloc[:, 61].unique()

array(['D'], dtype=object)

# 코드 마지막